### ISSUE TITLE
affix not working without offset in affix-options

### ISSUE THREAD

**Issue by fatcop** [mg/ngScrollSpy#17]
affix in demo's not working.

Seems that just having affix attrib without a affix-options containing an offset value doesn't set the default offset of 0.

SHA: e9aed4daffe1907c0acb063b8794f0d20764c40b

Fix that worked for me.

Line #20 of affix.js:
```javascript
affixOptions = angular.extend({offset: 0}, affixOptions);
```

**Comment by mg** [comment]
Merged in 1.06
