### ISSUE TITLE
Bower out of Sync

### ISSUE THREAD

**Issue by william-fuller** [mg/ngScrollSpy#20]
Downloading on http://mg.github.io/ngScrollSpy/ the version works perfectly fine. Doing a Bower save downloading v1.0.6 has a problem on line #219 in the ngScrollSpy.js which is missing `affixOptions =` Saw the issue has been updated 14 days ago but what is getting downloaded using Bower is out of sync.

**Comment by puttyman** [comment]
you can always install using the git repo. eg.

bower install https://github.com/mg/ngScrollSpy.git --save

**Comment by william-fuller** [comment]
Ok thanks, that's a lot better than doing an install on the actual commit which I was doing as a stop gap.

"ngScrollSpy": "git@github.com:mg/ngScrollSpy.git#847363b9a380d654c157d3431626474cad273438",
