### ISSUE TITLE
Suggestion: link to mgcrea's Angular Strap library

### ISSUE THREAD

**Issue by mattheworres** [mg/ngScrollSpy#27]
Hello,

I briefly used your library to perform affix type actions in my project, before I discovered some bugs and then you announced this project was abandoned (bummer!).

However, luckily I discovered that mgcrea's Angular Strap project - which is intended to be an Angular friendly drop-in replacement for the Bootstrap Javascript functions - has both a scroll spy and an affix component contained in it.

Better yet, the developer has been careful to make everything highly modularized. On the doc page, it will point to the dependencies each separate module has, so you can pick and choose the modules you need.

I for instance was able to replace this library with Angular Strap's affix functionality. Pretty lightweight, and effective.

Perhaps you can provide a link to mgcrea's library ( http://mgcrea.github.io/angular-strap/ ) on the Readme?

Thanks for your great library, and apologies that you had to abandon it.

**Comment by mg** [comment]
Thank you, I will provide a link to it. 

Sorry for the abandonment, but I've moved to React from Angular and given the time I have to devote to the family and work, I simply cannot afford to invest time and effort in the Angular ecosystem anymore. Besides, given the changes coming for 2.0, this will probably have to be rewritten from scratch.
