### ISSUE TITLE
Provide a way to offset from edge of screen

### ISSUE THREAD

**Issue by jondthompson** [mg/ngScrollSpy#7]
I want to be able to account for the fixed header I already have, so I want my div to stop when it is offset from the top. I currently have it 'bounce back' when the div hits the top via a position tag, but that causes a couple of strange behaviors.

**Comment by jeff-french** [comment]
+1

**Comment by eduardoinnorway** [comment]
please provide offset attribute, else this is not a good solution, many new apps have a fixed header.

**Comment by leonex-cstoller** [comment]
This has been implemented and merged in #16
You can use it this way:
```html
<div affix affix-options="{offset: 60}">[...]</div>
```

@mg I think this issue could be closed ;-)

**Comment by mg** [comment]
Thanks!
